### ISSUE TITLE
Permitir pausar el Plugin

### ISSUE THREAD

**Issue by nachoazulgrana** [lndgalante/mas-vendidos#1]
Pausar el plugin para no siempre nos lleve a la posición del producto mas vendido en Mercado Libre.

**Comment by lndgalante** [comment]
Gracias, lo vamos a solucionar!

**Comment by gaguirre** [comment]
Quizás haciendo #3 esté problema quedaría solucionado también.

**Comment by lndgalante** [comment]
También surgió la idea de que este dentro del menu "Más Relevantes - Menor precio - Mayor precio" una opción "Más vendidos". Que les parece?

**Comment by nachoazulgrana** [comment]
Me parece mucho más cómodo eso!

Enviado desde mi BlackBerry de Movistar (http://www.movistar.com.ar)

On Apr 6, 2017, 9:05 PM -0300, Leonardo Galante <notifications@github.com>, wrote:

También surgió la idea de que este dentro del menu "Más Relevantes - Menor precio - Mayor precio" una opción "Más vendidos". Que les parece?

**Comment by lndgalante** [comment]
Gracias a @erosilk (https://github.com/Fenwil/MercadoLibre-MasVendidos/pull/6) tenemos la opción de activar/desactivar la extensión 👏
