### ISSUE TITLE
El proyecto sigue activo?

### ISSUE THREAD

**Issue by Ambro17** [lndgalante/mas-vendidos#14]

**Comment by emilianox** [comment]
si buscas la ext en la store es este link https://chrome.google.com/webstore/detail/mercadolibre-m%C3%A1s-vendidos/bmjpjimlmmbjpmglplkahkhpebomdoed/related

**Comment by Ambro17** [comment]
Si, lo encontré de casualidad, aunque la funcionalidad que ofrece es distinta a la que muestra el screenshot

**Comment by lndgalante** [comment]
Hola @Ambro17 @emilianox el proyecto sigue funcionando, pero no he trabajado en nuevas funcionalidades, si quieren agregar o modificar código esta abierto para eso
