### ISSUE TITLE
innerText.includes busca también en el título

### ISSUE THREAD

**Issue by marcosfede** [lndgalante/mas-vendidos#2]
![image](https://cloud.githubusercontent.com/assets/16232610/24588288/bb8265c0-179b-11e7-8af8-fc6d949114af.png)

en este caso se estilan 2 rows distintas,  `row.innerText.includes(mostSelled)` busca tambien en el titulo de la publicación

quizás se podría hacer algo así
```javascript
  const row = rows.find(row => {
 let info = row.querySelector('.extra-info-sold')
 return info ? info.innerText.includes(mostSelled) : false
});
```

**Comment by lndgalante** [comment]
Es verdad! Probé y encontré este caso también:

<img width="996" alt="screen shot 2017-04-02 at 4 13 29 pm" src="https://cloud.githubusercontent.com/assets/2475912/24591180/9b25716a-17d1-11e7-984a-03c500561248.png" />

Como se ve encontró también 790 en el precio.

Gracias por la solución y último commit también mejora el nombre de las variables.
