### ISSUE TITLE
Ordenar por más vendidos

### ISSUE THREAD

**Issue by gaguirre** [lndgalante/mas-vendidos#3]
Sería muy bueno si se pudiese ordenar por cantidad de ventas, así poder ver no uno sino un top de más vendidos.

**Comment by lndgalante** [comment]
<img width="403" alt="screen shot 2017-04-04 at 7 40 24 am" src="https://cloud.githubusercontent.com/assets/2475912/24652909/ff6d265c-1909-11e7-87e1-3ef83f3dd14c.png">

Ya otros lo han pedido así que podría ser una gran idea!

**Comment by lndgalante** [comment]
@gaguirre cierro el Issue ya que la nueva versión `0.1.0` ordena de manera descendente la cantidad de ventas. Probala si te funciona bien. Apreciaría mucho code-review para uno de estos días 😉
