### ISSUE TITLE
El modo mosaico marca la primera publicación - sea la mas vendida o no.

### ISSUE THREAD

**Issue by mikirobles** [lndgalante/mas-vendidos#4]
Busqueda de ejemplo: http://listado.mercadolibre.com.ar/xbox_DisplayType_G#D[A:xbox]
Señala el primer link con 10 vendidos.

**Comment by lndgalante** [comment]
Hola @erosilk proba ahora la nueva versión 0.0.8 y decime si sigue el problema.

**Comment by mikirobles** [comment]
Ya funciona bien!

**Comment by lndgalante** [comment]
Buenísimo, gracias!
